# Generated by Django 5.1.10 on 2025-06-26 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("builder", "0002_aiplayer"),
        ("collection", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="deck",
            name="deck_u_user_name",
        ),
        migrations.AddField(
            model_name="deck",
            name="ai_player",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="builder.aiplayer",
            ),
        ),
        migrations.AlterField(
            model_name="deck",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="deck",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("ai_player__isnull", True), ("user__isnull", False)),
                    models.Q(("ai_player__isnull", False), ("user__isnull", True)),
                    _connector="OR",
                ),
                name="deck_exactly_one_owner",
            ),
        ),
        migrations.AddConstraint(
            model_name="deck",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", False)),
                fields=("user", "name"),
                name="deck_u_user_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="deck",
            constraint=models.UniqueConstraint(
                condition=models.Q(("ai_player__isnull", False)),
                fields=("ai_player", "name"),
                name="deck_u_ai_name",
            ),
        ),
    ]
