# Generated by Django 5.1.10 on 2025-07-23 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("builder", "0004_title_config"),
        ("collection", "0002_remove_deck_deck_u_user_name_deck_ai_player_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deck",
            name="title",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="builder.title",
            ),
        ),
    ]
