# Generated by Django 5.1.10 on 2025-07-23 22:02

from django.db import migrations

def populate_deck_titles(apps, schema_editor):
    """
    Populate the title field for all existing decks.
    Assign all existing decks to Title ID 1.
    """
    Deck = apps.get_model('collection', 'Deck')
    Title = apps.get_model('builder', 'Title')

    title = Title.objects.filter(id=1).first()
    if not title:
        return

    for deck in Deck.objects.all():
        deck.title = title
        deck.save()


class Migration(migrations.Migration):

    dependencies = [
        ("collection", "0003_deck_title"),
    ]

    operations = [
        migrations.RunPython(
            populate_deck_titles,
        ),
    ]
