# Generated by Django 5.1.10 on 2025-07-23 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("builder", "0004_title_config"),
        ("collection", "0004_populate_deck_titles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deck",
            name="title",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="builder.title"
            ),
        ),
    ]
