# Generated by Django 5.1.10 on 2025-09-13 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collection", "0005_alter_deck_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="deck",
            name="script",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
