# Generated by Django 5.1.10 on 2026-01-01 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collection", "0007_user_title_deck_preference"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="usertitledeckpreference",
            new_name="collection__user_id_252f8d_idx",
            old_name="collection_user_title_idx",
        ),
        migrations.AlterField(
            model_name="usertitledeckpreference",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
