# Generated by Django 5.1.10 on 2025-09-19 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("collection", "0008_rename_collection_user_title_idx_collection__user_id_252f8d_idx_and_more"),
        ("collection", "0008_user_title_deck_preference_last_friend"),
    ]

    operations = []
