# Generated by Codex on 2026-05-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collection", "0009_merge_0008_user_title_deck_preference_last_friend"),
    ]

    operations = [
        migrations.AddField(
            model_name="deck",
            name="slug",
            field=models.SlugField(blank=True, default=""),
        ),
    ]
