# Generated by Codex on 2026-05-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collection", "0010_deck_slug"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="deck",
            constraint=models.UniqueConstraint(
                condition=~models.Q(slug=""),
                fields=("title", "slug"),
                name="deck_u_title_slug_nonblank",
            ),
        ),
    ]
