# Generated by Codex on 2026-05-17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("collection", "0011_deck_slug_constraint"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="deck",
            name="deck_u_title_slug_nonblank",
        ),
        migrations.RemoveField(
            model_name="deck",
            name="slug",
        ),
    ]
