# Generated by Codex on 2026-05-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collection", "0012_remove_deck_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="deck",
            name="archived_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.RemoveConstraint(
            model_name="deck",
            name="deck_u_user_name",
        ),
        migrations.RemoveConstraint(
            model_name="deck",
            name="deck_u_ai_name",
        ),
        migrations.AddConstraint(
            model_name="deck",
            constraint=models.UniqueConstraint(
                condition=models.Q(archived_at__isnull=True, user__isnull=False),
                fields=("user", "name"),
                name="deck_u_user_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="deck",
            constraint=models.UniqueConstraint(
                condition=models.Q(ai_player__isnull=False, archived_at__isnull=True),
                fields=("ai_player", "name"),
                name="deck_u_ai_name",
            ),
        ),
    ]
