# Generated by Codex on 2026-07-04

from django.db import migrations, models


def hide_intro_scenario_decks(apps, schema_editor):
    Deck = apps.get_model("collection", "Deck")
    Deck.objects.filter(
        ai_player__name="Intro Scenario",
        name__startswith="Intro ",
    ).update(is_pve_opponent=False)


class Migration(migrations.Migration):

    dependencies = [
        ("collection", "0013_deck_archived_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="deck",
            name="is_pve_opponent",
            field=models.BooleanField(
                default=True,
                help_text=(
                    "Whether this AI deck appears in normal PvE opponent selection."
                ),
            ),
        ),
        migrations.RunPython(
            hide_intro_scenario_decks,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
