"""
Trait processing system for game cards.

This module processes game events and triggers trait effects like Charge,
Battlecry, Deathrattle, and manifest-defined triggered abilities.
"""

import logging
from typing import Callable

from pydantic import TypeAdapter, ValidationError

from apps.builder.schemas import Action, Trait
from apps.gameplay.schemas.engine import Rejected, Result, Success
from apps.gameplay.schemas.events import (
    ActionableEvent,
    CreatureDeathEvent,
    DamageEvent,
    Event,
    HealEvent,
    PlayEvent,
    SummonEvent,
)
from apps.gameplay.schemas.game import CardInPlay, Creature, GameState
from apps.gameplay.services import GameService

logger = logging.getLogger(__name__)


# Maps event types to source/snapshot traits that should trigger on those events.
EVENT_TRAIT_TRIGGERS = {
    "event_play": ["charge", "battlecry"],
    "event_creature_death": ["deathrattle"],
}

TRIGGER_EVENT_TYPES = {
    "card_played": {"event_play"},
    "creature_played": {"event_play", "event_summon"},
    "spell_used": {"event_play"},
    "damage": {"event_damage"},
    "heal": {"event_heal"},
    "creature_death": {"event_creature_death"},
    "hero_power_used": {"event_use_hero"},
}


def apply(state: GameState, event: Event) -> Result:
    """
    Process an event and return child effects generated by traits.

    Existing source-attached traits are processed first. Generic triggered traits
    are then evaluated against creatures currently on board, plus a damaged
    creature snapshot when lethal damage removed that creature from the board.
    """
    child_effects = []
    events = []

    legacy_result = _apply_source_traits(state, event)
    state = legacy_result.new_state
    events.extend(legacy_result.events)
    child_effects.extend(legacy_result.child_effects)

    for observer_side, observer_id, creature in _iter_trigger_observers(state, event):
        for trait in creature.traits:
            if trait.type != "triggered":
                continue
            if not _trigger_matches(
                state, event, observer_side, observer_id, creature, trait
            ):
                continue

            result = handle_triggered_trait(
                state=state,
                event=event,
                observer_side=observer_side,
                creature=creature,
                trait=trait,
            )
            state = result.new_state
            events.extend(result.events)
            child_effects.extend(result.child_effects)

    return Success(new_state=state, events=events, child_effects=child_effects)


def _apply_source_traits(state: GameState, event: Event) -> Success:
    child_effects = []
    events = []

    triggered_traits = EVENT_TRAIT_TRIGGERS.get(event.type, [])
    if not triggered_traits:
        return Success(new_state=state, events=[], child_effects=[])

    entity = _source_trait_entity(state, event)
    if not entity:
        return Success(new_state=state, events=[], child_effects=[])

    for trait in entity.traits:
        if trait.type not in triggered_traits:
            continue
        handler = TRAIT_HANDLERS.get(trait.type)
        if not handler:
            continue
        result = handler(state, event, entity, trait)
        if isinstance(result, Success):
            state = result.new_state
        events.extend(result.events)
        child_effects.extend(result.child_effects)

    return Success(new_state=state, events=events, child_effects=child_effects)


def _source_trait_entity(state: GameState, event: Event):
    if isinstance(event, CreatureDeathEvent):
        return event.creature
    if isinstance(event, PlayEvent):
        return state.cards.get(event.source_id)
    return None


def _iter_trigger_observers(state: GameState, event: Event):
    seen = set()
    for side in ("side_a", "side_b"):
        for creature_id in list(state.board[side]):
            creature = state.creatures.get(creature_id)
            if creature:
                seen.add(creature_id)
                yield side, creature_id, creature

    if not isinstance(event, DamageEvent):
        return
    if event.target_type != "creature" or event.target_id in seen:
        return
    if event.target_side and event.target_creature:
        yield event.target_side, event.target_id, event.target_creature


def _trigger_matches(
    state: GameState,
    event: Event,
    observer_side: str,
    observer_id: str,
    observer: Creature,
    trait: Trait,
) -> bool:
    when = getattr(trait, "when", None)
    if not when:
        return False

    if event.type not in TRIGGER_EVENT_TYPES.get(when.event, set()):
        return False

    if not _trigger_play_event_matches(state, event, when.event):
        return False

    return _entity_filter_matches(
        state=state,
        event=event,
        role="source",
        entity_filter=when.source,
        observer_side=observer_side,
        observer_id=observer_id,
        observer=observer,
        trigger_event=when.event,
    ) and _entity_filter_matches(
        state=state,
        event=event,
        role="target",
        entity_filter=when.target,
        observer_side=observer_side,
        observer_id=observer_id,
        observer=observer,
        trigger_event=when.event,
    )


def _trigger_play_event_matches(state: GameState, event: Event, trigger_event: str):
    if trigger_event == "creature_played":
        return _trigger_event_card_type(state, event) == "creature"
    if trigger_event == "spell_used":
        return _trigger_event_card_type(state, event) == "spell"
    return True


def _trigger_event_card_type(state: GameState, event: Event):
    if isinstance(event, PlayEvent):
        card_id = event.source_id
    elif isinstance(event, SummonEvent):
        card_id = event.target_id
    else:
        return None
    card = state.cards.get(card_id)
    return card.card_type if card else None


def _entity_filter_matches(
    *,
    state: GameState,
    event: Event,
    role: str,
    entity_filter,
    observer_side: str,
    observer_id: str,
    observer: Creature,
    trigger_event: str,
) -> bool:
    entity = _event_entity(state, event, role, trigger_event)
    if not entity:
        return not _filter_has_constraints(entity_filter)

    if entity_filter.kind and entity["kind"] != entity_filter.kind:
        return False

    if entity_filter.card_type and entity.get("card_type") != entity_filter.card_type:
        return False

    if (
        entity_filter.template_slug
        and entity.get("template_slug") != entity_filter.template_slug
    ):
        return False

    entity_is_observer = _entity_is_observer(entity, observer_id, observer)
    if entity_filter.self and not entity_is_observer:
        return False
    if entity_filter.exclude_self and entity_is_observer:
        return False

    if entity_filter.controller != "any":
        entity_side = entity.get("side")
        if entity_side is None:
            return False
        if entity_filter.controller == "self" and entity_side != observer_side:
            return False
        if entity_filter.controller == "opponent" and entity_side == observer_side:
            return False

    return True


def _filter_has_constraints(entity_filter) -> bool:
    return any(
        [
            entity_filter.kind,
            entity_filter.controller != "any",
            entity_filter.self,
            entity_filter.exclude_self,
            entity_filter.card_type,
            entity_filter.template_slug,
        ]
    )


def _entity_is_observer(entity: dict, observer_id: str, observer: Creature) -> bool:
    return (entity.get("kind") == "creature" and entity.get("id") == observer_id) or (
        entity.get("kind") == "card" and entity.get("id") == observer.card_id
    )


def _event_entity(
    state: GameState, event: Event, role: str, trigger_event: str
) -> dict | None:
    if trigger_event == "creature_played" and isinstance(event, SummonEvent):
        # For creature-entry triggers, filters describe the creature that entered,
        # just as they describe the played card for PlayEvent. Keep SummonEvent's
        # raw source fields unchanged so logs still attribute the summon to its
        # hero, spell, or creature.
        if role == "source":
            return _entity_details(
                state=state,
                kind="card",
                entity_id=event.target_id,
                side=event.side,
            )
        return None

    if role == "source":
        return _event_source_entity(state, event)
    return _event_target_entity(state, event)


def _event_source_entity(state: GameState, event: Event) -> dict | None:
    source_type = getattr(event, "source_type", None)
    source_id = getattr(event, "source_id", None)
    if not source_type or not source_id:
        return None

    side = getattr(event, "source_side", None) or getattr(event, "side", None)
    return _entity_details(
        state=state,
        kind=source_type,
        entity_id=source_id,
        side=side,
    )


def _event_target_entity(state: GameState, event: Event) -> dict | None:
    target_type = getattr(event, "target_type", None)
    target_id = getattr(event, "target_id", None)
    if not target_type or not target_id:
        return None

    side = getattr(event, "target_side", None)
    target_creature = (
        getattr(event, "target_creature", None)
        if isinstance(event, DamageEvent)
        else None
    )
    creature = None
    if target_type == "creature":
        creature = state.creatures.get(target_id) or target_creature
    if isinstance(event, CreatureDeathEvent):
        creature = event.creature

    return _entity_details(
        state=state,
        kind=target_type,
        entity_id=target_id,
        side=side,
        creature=creature,
    )


def _entity_details(
    *,
    state: GameState,
    kind: str,
    entity_id: str,
    side: str | None,
    creature: Creature | None = None,
) -> dict:
    details = {"kind": kind, "id": entity_id, "side": side}

    if kind == "card":
        card = state.cards.get(entity_id)
        if card:
            details["card_type"] = card.card_type
            details["template_slug"] = card.template_slug
        return details

    if kind == "creature":
        creature = creature or state.creatures.get(entity_id)
        if creature:
            details["card_id"] = creature.card_id
            card = state.cards.get(creature.card_id)
            if card:
                details["card_type"] = card.card_type
                details["template_slug"] = card.template_slug
        if details["side"] is None:
            details["side"] = _creature_side(state, entity_id)
        return details

    if kind == "hero":
        if details["side"] is None:
            details["side"] = _hero_side(state, entity_id)
        return details

    return details


def _creature_side(state: GameState, creature_id: str) -> str | None:
    for side in ("side_a", "side_b"):
        if creature_id in state.board[side]:
            return side
    return None


def _hero_side(state: GameState, hero_id: str) -> str | None:
    for side, hero in state.heroes.items():
        if hero.hero_id == hero_id:
            return side
    return None


def _trigger_action_event(observer_side: str, creature: Creature) -> ActionableEvent:
    return ActionableEvent(
        type="event_triggered",
        side=observer_side,
        source_type="creature",
        source_id=creature.creature_id,
        target_type=None,
        target_id=None,
    )


# ============================================================================
# Individual Trait Handlers
# ============================================================================


def handle_charge_trait(
    state: GameState,
    event: PlayEvent,
    card: CardInPlay,
    trait: Trait,
) -> Result:
    """
    Charge: Can attack immediately when played.
    """
    creature = state.creatures.get(event.creature_id)
    if not creature:
        return Rejected(reason=f"Creature {event.creature_id} does not exist")
    creature.exhausted = False
    return Success(new_state=state, events=[], child_effects=[])


def handle_battlecry_trait(
    state: GameState,
    event: PlayEvent,
    card: CardInPlay,
    trait: Trait,
) -> Result:
    """
    Battlecry: Effect triggers when card is played from hand.
    """
    child_effects = []

    for card_action in trait.actions:
        try:
            card_action = TypeAdapter(Action).validate_python(card_action)
        except ValidationError:
            logger.warning("Invalid card action: %s", card_action)
            continue

        child_effects.extend(
            GameService.compile_action(
                state=state,
                event=event,
                action=card_action,
            )
        )

    return Success(new_state=state, events=[], child_effects=child_effects)


def handle_deathrattle_trait(
    state: GameState,
    event: Event,
    creature: Creature,
    trait: Trait,
) -> Result:
    """
    Deathrattle: Effect triggers when card is destroyed.
    """
    child_effects = []

    for card_action in trait.actions:
        child_effects.extend(
            GameService.compile_action(
                state=state,
                event=event,
                action=card_action,
            )
        )

    return Success(new_state=state, events=[], child_effects=child_effects)


def handle_triggered_trait(
    *,
    state: GameState,
    event: Event,
    observer_side: str,
    creature: Creature,
    trait: Trait,
) -> Result:
    child_effects = []
    action_event = _trigger_action_event(observer_side, creature)

    for card_action in trait.actions:
        try:
            card_action = TypeAdapter(Action).validate_python(card_action)
        except ValidationError:
            logger.warning("Invalid triggered action: %s", card_action)
            continue

        child_effects.extend(
            GameService.compile_action(
                state=state,
                event=action_event,
                action=card_action,
                trigger_event=event,
            )
        )

    return Success(new_state=state, events=[], child_effects=child_effects)


TRAIT_HANDLERS: dict[str, Callable[[GameState, Event, CardInPlay, Trait], Result]] = {
    "charge": handle_charge_trait,
    "battlecry": handle_battlecry_trait,
    "deathrattle": handle_deathrattle_trait,
}
