# Generated by Django 5.1.10 on 2025-07-16 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "whitelist_mode_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="When enabled, only approved users can log in and use the site",
                    ),
                ),
                (
                    "signup_disabled",
                    models.BooleanField(
                        default=False,
                        help_text="When enabled, new user registrations are completely disabled",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Site Settings",
                "verbose_name_plural": "Site Settings",
            },
        ),
    ]
