# Generated by Django 5.1.10 on 2025-07-16 21:42

from django.db import migrations


def create_initial_site_settings(apps, schema_editor):
    """Create initial site settings with default values."""
    SiteSettings = apps.get_model('control', 'SiteSettings')
    SiteSettings.objects.get_or_create(
        pk=1,
        defaults={
            'whitelist_mode_enabled': False,
            'signup_disabled': False,
        }
    )


def reverse_create_initial_site_settings(apps, schema_editor):
    """Remove initial site settings."""
    SiteSettings = apps.get_model('control', 'SiteSettings')
    SiteSettings.objects.filter(pk=1).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            create_initial_site_settings,
            reverse_create_initial_site_settings
        ),
    ]
