# Generated by Django 5.1.10 on 2025-06-06 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Title",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField()),
                ("version", models.PositiveIntegerField()),
                ("is_latest", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HeroTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField()),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("is_latest", models.BooleanField(default=True)),
                ("health", models.PositiveIntegerField()),
                ("hero_power", models.JSONField(blank=True, default=dict)),
                ("spec", models.JSONField(blank=True, default=dict)),
                (
                    "title",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="builder.title"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CardTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField()),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("is_latest", models.BooleanField(default=True)),
                (
                    "card_type",
                    models.CharField(
                        choices=[("minion", "Minion"), ("spell", "Spell")],
                        db_index=True,
                        default="minion",
                        max_length=15,
                    ),
                ),
                ("cost", models.PositiveSmallIntegerField()),
                ("attack", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("health", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("spec", models.JSONField(blank=True, default=dict)),
                (
                    "title",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="builder.title"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddConstraint(
            model_name="title",
            constraint=models.UniqueConstraint(
                fields=("slug", "version"), name="u_slug_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="title",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_latest", True)),
                fields=("slug",),
                name="u_slug_latest_only_one",
            ),
        ),
        migrations.AddIndex(
            model_name="herotemplate",
            index=models.Index(
                fields=["title", "slug", "is_latest"],
                name="herotemplate_t_s_latest_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="herotemplate",
            constraint=models.UniqueConstraint(
                fields=("title", "slug", "version"),
                name="herotemplate_u_title_slug_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="herotemplate",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_latest", True)),
                fields=("title", "slug"),
                name="herotemplate_u_title_slug_latest_only_one",
            ),
        ),
        migrations.AddIndex(
            model_name="cardtemplate",
            index=models.Index(
                fields=["title", "slug", "is_latest"],
                name="cardtemplate_t_s_latest_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="cardtemplate",
            constraint=models.UniqueConstraint(
                fields=("title", "slug", "version"),
                name="cardtemplate_u_title_slug_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="cardtemplate",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_latest", True)),
                fields=("title", "slug"),
                name="cardtemplate_u_title_slug_latest_only_one",
            ),
        ),
    ]
