# Generated by Django 5.1.10 on 2025-06-25 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Faction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField()),
                ("name", models.CharField(max_length=40)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Title",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField()),
                ("version", models.PositiveIntegerField()),
                ("is_latest", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField()),
                ("name", models.CharField(max_length=40)),
                ("description", models.TextField(blank=True)),
                (
                    "title",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="builder.title"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HeroTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField()),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("is_latest", models.BooleanField(default=True)),
                ("health", models.PositiveIntegerField()),
                ("hero_power", models.JSONField(blank=True, default=dict)),
                ("spec", models.JSONField(blank=True, default=dict)),
                (
                    "faction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="builder.faction",
                    ),
                ),
                (
                    "title",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="builder.title"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="faction",
            name="title",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="builder.title"
            ),
        ),
        migrations.CreateModel(
            name="CardTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField()),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("is_latest", models.BooleanField(default=True)),
                (
                    "card_type",
                    models.CharField(
                        choices=[("minion", "Minion"), ("spell", "Spell")],
                        default="minion",
                        max_length=15,
                    ),
                ),
                ("cost", models.PositiveSmallIntegerField()),
                ("attack", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("health", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("spec", models.JSONField(blank=True, default=dict)),
                (
                    "faction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="builder.faction",
                    ),
                ),
                ("tags", models.ManyToManyField(blank=True, to="builder.tag")),
                (
                    "title",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="builder.title"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Trait",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "slug",
                    models.SlugField(
                        choices=[
                            ("armor", "Armor"),
                            ("battlecry", "Battlecry"),
                            ("charge", "Charge"),
                            ("cleave", "Cleave"),
                            ("deathrattle", "Deathrattle"),
                            ("inspire", "Inspire"),
                            ("lifesteal", "Lifesteal"),
                            ("ranged", "Ranged"),
                            ("taunt", "Taunt"),
                            ("unique", "Unique"),
                        ]
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                ("description", models.TextField(blank=True)),
                ("accepts_arguments", models.BooleanField(default=False)),
                ("argument_description", models.CharField(blank=True, max_length=100)),
                (
                    "title",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="builder.title"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CardTrait",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("data", models.JSONField(blank=True, default=dict)),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="builder.cardtemplate",
                    ),
                ),
                (
                    "trait",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="builder.trait"
                    ),
                ),
            ],
            options={
                "verbose_name": "Card Trait",
                "verbose_name_plural": "Card Traits",
            },
        ),
        migrations.AddField(
            model_name="cardtemplate",
            name="traits",
            field=models.ManyToManyField(
                blank=True, through="builder.CardTrait", to="builder.trait"
            ),
        ),
        migrations.AddConstraint(
            model_name="title",
            constraint=models.UniqueConstraint(
                fields=("slug", "version"), name="u_slug_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="title",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_latest", True)),
                fields=("slug",),
                name="u_slug_latest_only_one",
            ),
        ),
        migrations.AddIndex(
            model_name="herotemplate",
            index=models.Index(
                fields=["title", "slug", "is_latest"],
                name="herotemplate_t_s_latest_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="herotemplate",
            constraint=models.UniqueConstraint(
                fields=("title", "slug", "version"),
                name="herotemplate_u_title_slug_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="herotemplate",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_latest", True)),
                fields=("title", "slug"),
                name="herotemplate_u_title_slug_latest_only_one",
            ),
        ),
        migrations.AddIndex(
            model_name="trait",
            index=models.Index(fields=["name"], name="trait_name_idx"),
        ),
        migrations.AddIndex(
            model_name="cardtrait",
            index=models.Index(fields=["card"], name="cardtrait_card_idx"),
        ),
        migrations.AddIndex(
            model_name="cardtrait",
            index=models.Index(fields=["trait"], name="cardtrait_trait_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="cardtrait",
            unique_together={("card", "trait")},
        ),
        migrations.AddIndex(
            model_name="cardtemplate",
            index=models.Index(
                fields=["title", "slug", "is_latest"],
                name="cardtemplate_t_s_latest_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="cardtemplate",
            index=models.Index(
                fields=[
                    "title",
                    "is_latest",
                    "cost",
                    "card_type",
                    "attack",
                    "health",
                    "name",
                ],
                name="card_full_sort_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="cardtemplate",
            constraint=models.UniqueConstraint(
                fields=("title", "slug", "version"),
                name="cardtemplate_u_title_slug_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="cardtemplate",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_latest", True)),
                fields=("title", "slug"),
                name="cardtemplate_u_title_slug_latest_only_one",
            ),
        ),
    ]
