# Generated by Django 5.1.10 on 2025-06-23 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("builder", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Faction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField()),
                ("name", models.CharField(max_length=40)),
                ("description", models.TextField(blank=True)),
                (
                    "title",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="builder.title"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="cardtemplate",
            name="faction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="builder.faction",
            ),
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField()),
                ("name", models.CharField(max_length=40)),
                ("description", models.TextField(blank=True)),
                (
                    "title",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="builder.title"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="cardtemplate",
            name="tags",
            field=models.ManyToManyField(blank=True, to="builder.tag"),
        ),
        migrations.CreateModel(
            name="Trait",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "slug",
                    models.SlugField(
                        choices=[
                            ("armor", "Armor"),
                            ("battlecry", "Battlecry"),
                            ("charge", "Charge"),
                            ("cleave", "Cleave"),
                            ("deathrattle", "Deathrattle"),
                            ("inspire", "Inspire"),
                            ("lifesteal", "Lifesteal"),
                            ("ranged", "Ranged"),
                            ("taunt", "Taunt"),
                            ("unique", "Unique"),
                        ]
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                ("description", models.TextField(blank=True)),
                ("accepts_arguments", models.BooleanField(default=False)),
                ("argument_description", models.CharField(blank=True, max_length=100)),
                (
                    "title",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="builder.title"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="cardtemplate",
            name="traits",
            field=models.ManyToManyField(blank=True, to="builder.trait"),
        ),
        migrations.CreateModel(
            name="CardTraitArgument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("argument", models.PositiveSmallIntegerField()),
                ("extra_data", models.JSONField(blank=True, default=dict)),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="builder.cardtemplate",
                    ),
                ),
                (
                    "trait",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="builder.trait"
                    ),
                ),
            ],
            options={
                "verbose_name": "Card Trait Argument",
                "verbose_name_plural": "Card Trait Arguments",
                "unique_together": {("card", "trait")},
            },
        ),
    ]
