# Generated by Django 5.1.10 on 2025-07-11 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("builder", "0002_aiplayer"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Builder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("editor", "Editor"),
                            ("collaborator", "Collaborator"),
                        ],
                        default="editor",
                        help_text="Role of the builder in this title",
                        max_length=20,
                    ),
                ),
                (
                    "added_by",
                    models.ForeignKey(
                        help_text="User who added this builder to the title",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="added_builders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "title",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="builders",
                        to="builder.title",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="builder_titles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Builder",
                "verbose_name_plural": "Builders",
                "indexes": [
                    models.Index(fields=["title"], name="builder_title_idx"),
                    models.Index(fields=["user"], name="builder_user_idx"),
                ],
                "unique_together": {("title", "user")},
            },
        ),
    ]
