# Generated by Django 5.1.10 on 2025-06-23 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("builder", "0002_faction_cardtemplate_faction_tag_cardtemplate_tags_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="herotemplate",
            name="faction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="builder.faction",
            ),
        ),
        migrations.AlterField(
            model_name="cardtraitargument",
            name="argument",
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
