# Generated by Django 5.1.10 on 2025-07-15 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("builder", "0003_builder"),
    ]

    operations = [
        migrations.AddField(
            model_name="title",
            name="config",
            field=models.JSONField(default=dict),
        ),
    ]
