# Generated by Django 5.1.10 on 2025-06-24 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("builder", "0003_herotemplate_faction_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cardtemplate",
            name="card_type",
            field=models.CharField(
                choices=[("minion", "Minion"), ("spell", "Spell")],
                default="minion",
                max_length=15,
            ),
        ),
        migrations.AddIndex(
            model_name="cardtemplate",
            index=models.Index(
                fields=[
                    "title",
                    "is_latest",
                    "cost",
                    "card_type",
                    "attack",
                    "health",
                    "name",
                ],
                name="card_full_sort_idx",
            ),
        ),
    ]
