# Generated by Django 5.1.10 on 2025-06-24 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("builder", "0004_alter_cardtemplate_card_type_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="trait",
            index=models.Index(fields=["name"], name="trait_name_idx"),
        ),
    ]
