# Generated by Django 5.1.10 on 2025-07-24 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("builder", "0004_title_config"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aiplayer",
            name="strategy_config",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="AI strategy parameters like aggression, card priorities, etc.",
            ),
        ),
    ]
