# Generated by Django 5.1.10 on 2025-08-06 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("builder", "0005_alter_aiplayer_strategy_config"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aiplayer",
            name="hero",
        ),
    ]
