# Generated by Django 5.1.10 on 2025-08-23 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("builder", "0006_remove_aiplayer_hero"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trait",
            name="slug",
            field=models.SlugField(
                choices=[
                    ("armor", "Armor"),
                    ("battlecry", "Battlecry"),
                    ("berserk", "Berserk"),
                    ("cant_attack", "Cant_attack"),
                    ("charge", "Charge"),
                    ("cleave", "Cleave"),
                    ("deathrattle", "Deathrattle"),
                    ("flying", "Flying"),
                    ("inspire", "Inspire"),
                    ("lifesteal", "Lifesteal"),
                    ("ranged", "Ranged"),
                    ("regeneration", "Regeneration"),
                    ("shield", "Shield"),
                    ("spellpower", "Spellpower"),
                    ("stealth", "Stealth"),
                    ("taunt", "Taunt"),
                    ("unique", "Unique"),
                    ("venom", "Venom"),
                    ("vigilance", "Vigilance"),
                ]
            ),
        ),
    ]
