# Generated by Django 5.1.10 on 2025-09-05 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("builder", "0007_alter_trait_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trait",
            name="accepts_arguments",
        ),
        migrations.RemoveField(
            model_name="trait",
            name="argument_description",
        ),
        migrations.AlterField(
            model_name="cardtemplate",
            name="cost",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="title",
            name="version",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="trait",
            name="slug",
            field=models.SlugField(
                choices=[
                    ("armor", "Armor"),
                    ("battlecry", "Battlecry"),
                    ("charge", "Charge"),
                    ("cleave", "Cleave"),
                    ("deathrattle", "Deathrattle"),
                    ("inspire", "Inspire"),
                    ("lifesteal", "Lifesteal"),
                    ("ranged", "Ranged"),
                    ("taunt", "Taunt"),
                    ("unique", "Unique"),
                ]
            ),
        ),
    ]
