# Generated by Django 5.1.10 on 2025-09-13 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("builder", "0008_remove_trait_argument_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trait",
            name="name",
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
