# Generated by Django 5.1.10 on 2025-12-07 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("builder", "0011_add_per_title_ratings"),
    ]

    operations = [
        migrations.AddField(
            model_name="cardtemplate",
            name="is_collectible",
            field=models.BooleanField(
                default=True,
                help_text="If False, this card cannot be added to player decks",
            ),
        ),
    ]
