# Generated by Codex on 2026-05-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("builder", "0012_add_is_collectible_to_cardtemplate"),
    ]

    operations = [
        migrations.AddField(
            model_name="cardtemplate",
            name="allowed_heroes",
            field=models.ManyToManyField(
                blank=True,
                help_text="If empty, this card can be used by any hero for the title.",
                related_name="specific_cards",
                to="builder.herotemplate",
            ),
        ),
    ]
