# Generated by Django 5.1.10 on 2026-07-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("builder", "0013_cardtemplate_allowed_heroes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cardtrait",
            name="trait_slug",
            field=models.SlugField(
                choices=[
                    ("armor", "Armor"),
                    ("battlecry", "Battlecry"),
                    ("charge", "Charge"),
                    ("cleave", "Cleave"),
                    ("deathrattle", "Deathrattle"),
                    ("inspire", "Inspire"),
                    ("lifesteal", "Lifesteal"),
                    ("ranged", "Ranged"),
                    ("stealth", "Stealth"),
                    ("taunt", "Taunt"),
                    ("triggered", "Triggered"),
                    ("unique", "Unique"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="traitoverride",
            name="slug",
            field=models.SlugField(
                choices=[
                    ("armor", "Armor"),
                    ("battlecry", "Battlecry"),
                    ("charge", "Charge"),
                    ("cleave", "Cleave"),
                    ("deathrattle", "Deathrattle"),
                    ("inspire", "Inspire"),
                    ("lifesteal", "Lifesteal"),
                    ("ranged", "Ranged"),
                    ("stealth", "Stealth"),
                    ("taunt", "Taunt"),
                    ("triggered", "Triggered"),
                    ("unique", "Unique"),
                ]
            ),
        ),
    ]
