# Generated by Django 5.1.10 on 2025-07-16 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_alter_user_managers_remove_user_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("suspended", "Suspended"),
                    ("banned", "Banned"),
                ],
                default="pending",
                help_text="User approval status for site access control",
                max_length=20,
            ),
        ),
    ]
