# Generated by Django 5.1.10 on 2025-07-16 21:42

from django.db import migrations


def set_existing_superusers_approved(apps, schema_editor):
    """Set existing superusers to approved status."""
    User = apps.get_model('authentication', 'User')
    User.objects.filter(is_superuser=True).update(status='approved')


def reverse_set_existing_superusers_approved(apps, schema_editor):
    """Reverse the migration - set superusers back to pending."""
    User = apps.get_model('authentication', 'User')
    User.objects.filter(is_superuser=True).update(status='pending')


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_status'),
    ]

    operations = [
        migrations.RunPython(
            set_existing_superusers_approved,
            reverse_set_existing_superusers_approved
        ),
    ]
