# Generated by Django 5.1.10 on 2025-10-28 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0005_friendship"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="elo_rating",
            field=models.IntegerField(
                default=1200,
                help_text="Player's ELO rating for PvP matches (default: 1200)",
            ),
        ),
    ]
