# Generated by Django 5.1.10 on 2025-10-28 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0006_add_elo_rating"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="elo_rating",
        ),
    ]
