# Generated by Django 5.1.10 on 2025-06-25 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("collection", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("init", "Init"),
                            ("in_progress", "In_progress"),
                            ("ended", "Ended"),
                        ],
                        default="init",
                        max_length=20,
                    ),
                ),
                ("state", models.JSONField(default=dict)),
                (
                    "side_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="games_as_side_a",
                        to="collection.deck",
                    ),
                ),
                (
                    "side_b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="games_as_side_b",
                        to="collection.deck",
                    ),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="games_won",
                        to="collection.deck",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
