# Generated by Django 5.1.10 on 2025-09-24 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gameplay", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GameUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("update", models.JSONField()),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="gameplay.game"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
