# Generated by Django 5.1.10 on 2025-10-06 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gameplay", "0002_gameupdate"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="queue",
            field=models.JSONField(default=list),
        ),
    ]
