# Generated by Django 5.1.10 on 2025-10-28 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gameplay", "0003_game_queue"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ELORatingChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("winner_old_rating", models.IntegerField()),
                ("winner_new_rating", models.IntegerField()),
                ("winner_rating_change", models.IntegerField()),
                ("loser_old_rating", models.IntegerField()),
                ("loser_new_rating", models.IntegerField()),
                ("loser_rating_change", models.IntegerField()),
                (
                    "game",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="elo_change",
                        to="gameplay.game",
                    ),
                ),
                (
                    "loser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="elo_losses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="elo_wins",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "ELO Rating Change",
                "verbose_name_plural": "ELO Rating Changes",
                "db_table": "gameplay_elo_rating_change",
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="gameplay_el_created_3e3026_idx"
                    ),
                    models.Index(
                        fields=["winner"], name="gameplay_el_winner__6946e5_idx"
                    ),
                    models.Index(
                        fields=["loser"], name="gameplay_el_loser_i_3929e7_idx"
                    ),
                ],
            },
        ),
    ]
