# Generated by Django 5.1.10 on 2025-10-28 21:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("builder", "0011_add_per_title_ratings"),
        ("gameplay", "0004_add_elo_rating_change"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserTitleRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "elo_rating",
                    models.IntegerField(
                        default=1200,
                        help_text="Player's ELO rating for this title (default: 1200)",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Title Rating",
                "verbose_name_plural": "User Title Ratings",
                "db_table": "gameplay_user_title_rating",
            },
        ),
        migrations.AddField(
            model_name="eloratingchange",
            name="title",
            field=models.ForeignKey(
                blank=True,
                help_text="The title this rating change is for",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="elo_changes",
                to="builder.title",
            ),
        ),
        migrations.AddIndex(
            model_name="eloratingchange",
            index=models.Index(fields=["title"], name="gameplay_el_title_i_355b98_idx"),
        ),
        migrations.AddField(
            model_name="usertitlerating",
            name="title",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_ratings",
                to="builder.title",
            ),
        ),
        migrations.AddField(
            model_name="usertitlerating",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="title_ratings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="usertitlerating",
            index=models.Index(
                fields=["title", "-elo_rating"], name="gameplay_us_title_i_6936af_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usertitlerating",
            index=models.Index(fields=["user"], name="gameplay_us_user_id_51a4e7_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="usertitlerating",
            unique_together={("user", "title")},
        ),
    ]
