# Generated by Django 5.1.10 on 2025-11-14 23:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collection", "0006_deck_script"),
        ("gameplay", "0005_add_per_title_ratings"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MatchmakingQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("matched", "Matched"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="queued",
                        help_text="Current status of the queue entry",
                        max_length=20,
                    ),
                ),
                (
                    "elo_rating",
                    models.IntegerField(
                        help_text="User's ELO rating at the time of queueing (for matchmaking)"
                    ),
                ),
                (
                    "deck",
                    models.ForeignKey(
                        help_text="The deck the user will use for the match",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matchmaking_queue_entries",
                        to="collection.deck",
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        blank=True,
                        help_text="The game created from this matchmaking",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="matchmaking_queue_entries",
                        to="gameplay.game",
                    ),
                ),
                (
                    "matched_with",
                    models.ForeignKey(
                        blank=True,
                        help_text="The queue entry this user was matched with",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="match_partner",
                        to="gameplay.matchmakingqueue",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user queuing for a match",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matchmaking_queue_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Matchmaking Queue Entry",
                "verbose_name_plural": "Matchmaking Queue Entries",
                "db_table": "gameplay_matchmaking_queue",
                "indexes": [
                    models.Index(
                        fields=["status", "elo_rating"],
                        name="gameplay_ma_status_9a7f06_idx",
                    ),
                    models.Index(
                        fields=["user", "status"], name="gameplay_ma_user_id_848543_idx"
                    ),
                    models.Index(
                        fields=["-created_at"], name="gameplay_ma_created_07bf82_idx"
                    ),
                ],
            },
        ),
    ]
