# Generated by Django 5.1.10 on 2025-12-02 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gameplay", "0007_friendly_challenges"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlayerNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "gameplay_player_notification",
            },
        ),
        migrations.RenameIndex(
            model_name="friendlychallenge",
            new_name="gameplay_fr_status_d4d312_idx",
            old_name="gameplay_fr_status__6a03a4_idx",
        ),
        migrations.RenameIndex(
            model_name="friendlychallenge",
            new_name="gameplay_fr_challen_d90c27_idx",
            old_name="gameplay_fr_challen_1de358_idx",
        ),
        migrations.AddField(
            model_name="game",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pve", "Pve"),
                    ("ranked", "Ranked"),
                    ("friendly", "Friendly"),
                ],
                default="pve",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="friendlychallenge",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("cancelled", "Cancelled"),
                    ("expired", "Expired"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="playernotification",
            name="game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="gameplay.game",
            ),
        ),
        migrations.AddField(
            model_name="playernotification",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="playernotification",
            index=models.Index(
                fields=["user", "is_read"], name="gameplay_pl_user_id_391b5d_idx"
            ),
        ),
    ]
