# Generated by Django 5.1.10 on 2025-12-02 20:34

from django.db import migrations


def populate_game_type(apps, schema_editor):
    """
    Populate the type field based on is_friendly and whether the game has two user players.

    Logic:
    - is_friendly=True → 'friendly'
    - is_friendly=False and two user players (neither deck is AI) → 'ranked'
    - everything else → 'pve'
    """
    Game = apps.get_model('gameplay', 'Game')

    # Update friendly games
    Game.objects.filter(is_friendly=True).update(type='friendly')

    # Update ranked games (not friendly, and both players are human)
    # A game has two user players if neither side_a nor side_b has an ai_player
    Game.objects.filter(
        is_friendly=False,
        side_a__ai_player__isnull=True,
        side_b__ai_player__isnull=True
    ).update(type='ranked')

    # Update PvE games (everything else that hasn't been set)
    Game.objects.filter(type__isnull=True).update(type='pve')


def reverse_populate_game_type(apps, schema_editor):
    """Reverse migration - set type back to None"""
    Game = apps.get_model('gameplay', 'Game')
    Game.objects.all().update(type=None)


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0008_add_game_type_field'),
    ]

    operations = [
        migrations.RunPython(populate_game_type, reverse_populate_game_type),
    ]
