# Generated by Django 5.1.10 on 2025-12-02 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0009_populate_game_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='type',
            field=models.CharField(
                choices=[
                    ('pve', 'Pve'),
                    ('ranked', 'Ranked'),
                    ('friendly', 'Friendly'),
                ],
                default='pve',
                max_length=20,
            ),
        ),
    ]
