# Generated by Django 5.1.10 on 2025-12-02 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gameplay", "0010_make_game_type_non_nullable"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="is_friendly",
        ),
    ]
