# Generated by Django 5.1.10 on 2025-12-02 21:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("builder", "0011_add_per_title_ratings"),
        ("gameplay", "0011_remove_is_friendly"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="player_a_ai",
            field=models.ForeignKey(
                blank=True,
                help_text="AI player on side_a (denormalized from side_a.ai_player)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="games_as_ai_a",
                to="builder.aiplayer",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="player_a_user",
            field=models.ForeignKey(
                blank=True,
                help_text="User on side_a (denormalized from side_a.user)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="games_as_player_a",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="player_b_ai",
            field=models.ForeignKey(
                blank=True,
                help_text="AI player on side_b (denormalized from side_b.ai_player)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="games_as_ai_b",
                to="builder.aiplayer",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="player_b_user",
            field=models.ForeignKey(
                blank=True,
                help_text="User on side_b (denormalized from side_b.user)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="games_as_player_b",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="title",
            field=models.ForeignKey(
                blank=True,
                help_text="The title this game is for (denormalized from side_a.title)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="games",
                to="builder.title",
            ),
        ),
    ]
