# Generated by Django 5.1.10 on 2025-12-02 21:14

from django.db import migrations


def populate_denormalized_fields(apps, schema_editor):
    """
    Populate denormalized fields from side_a and side_b.
    """
    Game = apps.get_model('gameplay', 'Game')
    Deck = apps.get_model('collection', 'Deck')

    # Update all games in batches using bulk_update for efficiency
    games = Game.objects.select_related('side_a', 'side_b').all()
    games_to_update = []

    for game in games:
        # Title is same for both sides (validated elsewhere)
        if game.side_a_id:
            # Refresh side_a to get related fields
            side_a = Deck.objects.select_related('user', 'title').get(pk=game.side_a_id)
            game.title_id = side_a.title_id
            game.player_a_user_id = side_a.user_id

        if game.side_b_id:
            # Refresh side_b to get related fields
            side_b = Deck.objects.select_related('user').get(pk=game.side_b_id)
            game.player_b_user_id = side_b.user_id

        games_to_update.append(game)

    # Bulk update to avoid triggering save() method
    Game.objects.bulk_update(
        games_to_update,
        ['title_id', 'player_a_user_id', 'player_b_user_id'],
        batch_size=500
    )


def reverse_populate_denormalized_fields(apps, schema_editor):
    """Reverse migration - set denormalized fields back to None"""
    Game = apps.get_model('gameplay', 'Game')
    Game.objects.all().update(
        title=None,
        player_a_user=None,
        player_b_user=None,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0012_add_denormalized_fields'),
    ]

    operations = [
        migrations.RunPython(populate_denormalized_fields, reverse_populate_denormalized_fields),
    ]
