# Generated by Django 5.1.10 on 2025-12-02 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0013_populate_denormalized_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='title',
            field=models.ForeignKey(
                help_text='The title this game is for (denormalized from side_a.title)',
                on_delete=models.PROTECT,
                related_name='games',
                to='builder.title',
            ),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['title', 'type'], name='gameplay_ga_title_type_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['title', 'player_a_user', 'player_b_user'], name='gameplay_ga_title_users_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['player_a_user', 'type'], name='gameplay_ga_player_a_type_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['player_b_user', 'type'], name='gameplay_ga_player_b_type_idx'),
        ),
    ]
