# Generated by Django 5.1.10 on 2025-12-02 21:14

import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0014_make_title_non_nullable_add_indexes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='player_a_ai',
        ),
        migrations.RemoveField(
            model_name='game',
            name='player_b_ai',
        ),
    ]
