# Generated by Django 5.1.10 on 2025-12-19 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gameplay", "0015_remove_ai_fields"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="game",
            name="gameplay_ga_title_type_idx",
        ),
        migrations.RemoveIndex(
            model_name="game",
            name="gameplay_ga_title_users_idx",
        ),
        migrations.RemoveIndex(
            model_name="game",
            name="gameplay_ga_player_a_type_idx",
        ),
        migrations.RemoveIndex(
            model_name="game",
            name="gameplay_ga_player_b_type_idx",
        ),
        migrations.AddField(
            model_name="game",
            name="time_per_turn",
            field=models.IntegerField(
                blank=True,
                help_text="Time limit per turn in seconds (null = no limit)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="turn_start_time",
            field=models.DateTimeField(
                blank=True,
                help_text="When the current turn started (for time enforcement)",
                null=True,
            ),
        ),
    ]
