# Generated by Django 5.1.10 on 2025-12-22 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gameplay", "0016_add_time_control_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="time_per_turn",
        ),
        migrations.RenameField(
            model_name="game",
            old_name="turn_start_time",
            new_name="turn_expires",
        ),
        migrations.AlterField(
            model_name="game",
            name="turn_expires",
            field=models.DateTimeField(
                blank=True,
                help_text="When the current turn expires (for time enforcement)",
                null=True,
            ),
        ),
    ]
