# Generated by Django 5.1.10 on 2025-11-23 18:10

from django.db import migrations, models


def set_ranked_games_to_rapid(apps, schema_editor):
    Game = apps.get_model("gameplay", "Game")
    Game.objects.filter(type="ranked", ladder_type__isnull=True).update(ladder_type="rapid")


def unset_ranked_games_ladder_type(apps, schema_editor):
    Game = apps.get_model("gameplay", "Game")
    Game.objects.filter(type="ranked", ladder_type="rapid").update(ladder_type=None)


class Migration(migrations.Migration):

    dependencies = [
        ("gameplay", "0018_setup_expired_turns_periodic_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="ladder_type",
            field=models.CharField(
                blank=True,
                choices=[("rapid", "Rapid"), ("daily", "Daily")],
                help_text="Ladder type for ranked games (rapid or daily).",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="eloratingchange",
            name="ladder_type",
            field=models.CharField(
                choices=[("rapid", "Rapid"), ("daily", "Daily")],
                default="rapid",
                help_text="Which ladder this rating change applies to.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="matchmakingqueue",
            name="ladder_type",
            field=models.CharField(
                choices=[("rapid", "Rapid"), ("daily", "Daily")],
                default="rapid",
                help_text="Which ladder this queue entry is for.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="usertitlerating",
            name="ladder_type",
            field=models.CharField(
                choices=[("rapid", "Rapid"), ("daily", "Daily")],
                default="rapid",
                help_text="Which ladder this rating applies to.",
                max_length=20,
            ),
        ),
        migrations.RunPython(set_ranked_games_to_rapid, unset_ranked_games_ladder_type),
        migrations.RemoveIndex(
            model_name="usertitlerating",
            name="gameplay_us_title_i_6936af_idx",
        ),
        migrations.RemoveIndex(
            model_name="usertitlerating",
            name="gameplay_us_user_id_51a4e7_idx",
        ),
        migrations.AddIndex(
            model_name="usertitlerating",
            index=models.Index(
                fields=["title", "ladder_type", "-elo_rating"],
                name="gameplay_us_title_ladder_elo_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="usertitlerating",
            index=models.Index(
                fields=["user", "ladder_type"],
                name="gameplay_us_user_ladder_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="usertitlerating",
            unique_together={("user", "title", "ladder_type")},
        ),
        migrations.AddIndex(
            model_name="eloratingchange",
            index=models.Index(
                fields=["title", "ladder_type"],
                name="gameplay_el_title_ladder_idx",
            ),
        ),
        migrations.RemoveIndex(
            model_name="matchmakingqueue",
            name="gameplay_ma_status_9a7f06_idx",
        ),
        migrations.RemoveIndex(
            model_name="matchmakingqueue",
            name="gameplay_ma_user_id_848543_idx",
        ),
        migrations.AddIndex(
            model_name="matchmakingqueue",
            index=models.Index(
                fields=["status", "ladder_type", "elo_rating"],
                name="gameplay_ma_status_ladder_elo_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="matchmakingqueue",
            index=models.Index(
                fields=["user", "status", "ladder_type"],
                name="gameplay_ma_user_status_ladder_idx",
            ),
        ),
    ]
