# Generated by Django 5.1.10 on 2026-01-01 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gameplay", "0019_add_ladder_types"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="eloratingchange",
            new_name="gameplay_el_title_i_0f86ca_idx",
            old_name="gameplay_el_title_ladder_idx",
        ),
        migrations.RenameIndex(
            model_name="matchmakingqueue",
            new_name="gameplay_ma_status_267c07_idx",
            old_name="gameplay_ma_status_ladder_elo_idx",
        ),
        migrations.RenameIndex(
            model_name="matchmakingqueue",
            new_name="gameplay_ma_user_id_caf4b3_idx",
            old_name="gameplay_ma_user_status_ladder_idx",
        ),
        migrations.RenameIndex(
            model_name="usertitlerating",
            new_name="gameplay_us_title_i_d2f999_idx",
            old_name="gameplay_us_title_ladder_elo_idx",
        ),
        migrations.RenameIndex(
            model_name="usertitlerating",
            new_name="gameplay_us_user_id_68a375_idx",
            old_name="gameplay_us_user_ladder_idx",
        ),
    ]
