# Generated by Django 5.1.10 on 2025-11-23 21:15

from django.db import migrations


def fix_duplicate_hero_ids(apps, schema_editor):
    Game = apps.get_model("gameplay", "Game")

    for game in Game.objects.iterator():
        state = game.state or {}
        heroes = state.get("heroes") or {}
        hero_a = heroes.get("side_a") or {}
        hero_b = heroes.get("side_b") or {}

        hero_id_a = hero_a.get("hero_id")
        hero_id_b = hero_b.get("hero_id")
        if not hero_id_a or not hero_id_b or hero_id_a != hero_id_b:
            continue

        new_hero_id_a = f"hero_{game.side_a_id}_a"
        new_hero_id_b = f"hero_{game.side_b_id}_b"

        hero_a["hero_id"] = new_hero_id_a
        hero_b["hero_id"] = new_hero_id_b
        heroes["side_a"] = hero_a
        heroes["side_b"] = hero_b
        state["heroes"] = heroes

        game.state = state
        game.save(update_fields=["state"])


class Migration(migrations.Migration):

    dependencies = [
        ("gameplay", "0020_rename_gameplay_el_title_ladder_idx_gameplay_el_title_i_0f86ca_idx_and_more"),
    ]

    operations = [
        migrations.RunPython(fix_duplicate_hero_ids, migrations.RunPython.noop),
    ]
