# Generated by Django 5.1.10 on 2026-01-01 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "collection",
            "0008_rename_collection_user_title_idx_collection__user_id_252f8d_idx_and_more",
        ),
        ("gameplay", "0021_fix_duplicate_hero_ids"),
    ]

    operations = [
        migrations.AlterField(
            model_name="friendlychallenge",
            name="challengee_deck",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="as_challengee_in_challenges",
                to="collection.deck",
            ),
        ),
        migrations.AlterField(
            model_name="friendlychallenge",
            name="challenger_deck",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="as_challenger_in_challenges",
                to="collection.deck",
            ),
        ),
    ]
