# Generated by Django 5.1 on 2026-01-15 00:00

from django.db import migrations, models

from apps.core.models import list_to_choices


class Migration(migrations.Migration):

    dependencies = [
        ("gameplay", "0022_alter_friendlychallenge_challengee_deck_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="status",
            field=models.CharField(
                choices=list_to_choices(['init', 'in_progress', 'ended', 'aborted']),
                default="init",
                max_length=20,
            ),
        ),
    ]
