# Generated by Django 5.1.10 on 2026-04-19 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gameplay", "0023_add_aborted_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="friendlychallenge",
            name="rematch_of",
            field=models.ForeignKey(
                blank=True,
                help_text="If set, this challenge is a rematch of the referenced game; sides are deterministically swapped on accept.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rematch_challenges",
                to="gameplay.game",
            ),
        ),
    ]
