# Generated by Codex on 2026-05-16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gameplay", "0024_friendlychallenge_rematch_of"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="ruleset_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Hash of engine/content compatibility for this game.",
                max_length=64,
            ),
        ),
        migrations.CreateModel(
            name="GameAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ruleset_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                (
                    "actor_side",
                    models.CharField(
                        choices=[("side_a", "Side_a"), ("side_b", "Side_b")],
                        max_length=10,
                    ),
                ),
                (
                    "actor_kind",
                    models.CharField(
                        choices=[
                            ("human", "Human"),
                            ("scripted_ai", "Scripted_ai"),
                            ("model_ai", "Model_ai"),
                            ("system", "System"),
                        ],
                        default="human",
                        max_length=20,
                    ),
                ),
                ("turn", models.PositiveIntegerField(default=0)),
                ("phase", models.CharField(blank=True, default="", max_length=20)),
                ("command", models.JSONField(default=dict)),
                ("legal_commands", models.JSONField(blank=True, default=list)),
                (
                    "pre_state_hash",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "post_state_hash",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("skipped", "Skipped"),
                        ],
                        default="accepted",
                        max_length=20,
                    ),
                ),
                ("error", models.JSONField(blank=True, default=dict)),
                (
                    "final_winner",
                    models.CharField(blank=True, default="", max_length=10),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="gameplay.game",
                    ),
                ),
            ],
            options={
                "db_table": "gameplay_game_action",
                "indexes": [
                    models.Index(
                        fields=["game", "created_at"],
                        name="gameplay_ga_game_id_37ad9c_idx",
                    ),
                    models.Index(
                        fields=["ruleset_id", "actor_side"],
                        name="gameplay_ga_ruleset_89d73d_idx",
                    ),
                    models.Index(
                        fields=["actor_kind", "created_at"],
                        name="gameplay_ga_actor_k_9063a0_idx",
                    ),
                ],
            },
        ),
    ]
