# Generated by Codex on 2026-05-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gameplay", "0025_agent_plumbing"),
    ]

    operations = [
        migrations.AddField(
            model_name="gameaction",
            name="observation",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Player-perspective observation at decision time for training.",
            ),
        ),
    ]
