# Generated by Codex on 2026-06-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gameplay", "0026_gameaction_observation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="type",
            field=models.CharField(
                choices=[
                    ("pve", "Pve"),
                    ("ranked", "Ranked"),
                    ("friendly", "Friendly"),
                    ("intro", "Intro"),
                ],
                default="pve",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="guest_access_token_hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="SHA-256 hash for single-game guest access.",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="guest_access_side",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Side granted by the guest access token.",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="guest_access_expires_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Expiry time for single-game guest access.",
                null=True,
            ),
        ),
    ]
