# Generated by Codex on 2026-06-21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("gameplay", "0027_game_guest_access"),
    ]

    operations = [
        migrations.CreateModel(
            name="PushDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("token", models.CharField(max_length=255)),
                (
                    "platform",
                    models.CharField(
                        choices=[("ios", "Ios")], default="ios", max_length=20
                    ),
                ),
                ("bundle_id", models.CharField(blank=True, default="", max_length=255)),
                (
                    "environment",
                    models.CharField(
                        choices=[
                            ("sandbox", "Sandbox"),
                            ("production", "Production"),
                        ],
                        default="production",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "last_seen_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("last_error", models.TextField(blank=True, default="")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="push_devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "gameplay_push_device",
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"],
                        name="gameplay_pu_user_id_b1d806_idx",
                    ),
                    models.Index(fields=["token"], name="gameplay_pu_token_7b9001_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="PushNotificationEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("turn_ready", "Turn_ready"),
                            ("friend_challenge", "Friend_challenge"),
                            ("match_started", "Match_started"),
                        ],
                        max_length=40,
                    ),
                ),
                ("dedupe_key", models.CharField(max_length=255, unique=True)),
                ("title", models.CharField(max_length=120)),
                ("body", models.CharField(max_length=240)),
                ("data", models.JSONField(blank=True, default=dict)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True, default="")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="push_notification_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "gameplay_push_notification_event",
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="gameplay_pu_user_id_975f67_idx",
                    ),
                    models.Index(
                        fields=["notification_type", "-created_at"],
                        name="gameplay_pu_notific_860a26_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="pushdevice",
            constraint=models.UniqueConstraint(
                fields=("token", "environment", "bundle_id"),
                name="gameplay_push_device_token_env_bundle_unique",
            ),
        ),
    ]
